### ISSUE TITLE
millitime()

### ISSUE THREAD

**Issue by lizhenghn123** [ideawu/sim#2]
In double millitime()(sim.h, line 27),:
    "double ret = now.tv_sec + now.tv_usec/1000.0/1000.0;"
It should be;
    "double ret = now.tv_sec * 1000 + now.tv_usec / 1000.0; "

**Comment by ideawu** [comment]
ok, I change it to `microtime()`, because it works as PHP's `microtime(true)`;

`microtime()` 

> returns a float(double), which represents the current time in seconds since the Unix epoch accurate to the nearest microsecond.
