### ISSUE TITLE
大概的读完了sim的代码，简单说一下个人的感受

### ISSUE THREAD

**Issue by lanyuliuyun** [ideawu/sim#5]
大概的读完了sim的代码，简单说一下个人的感受：
1，Link主体表示一个tcp连接对象，但却又包含了客户端的connect工厂方法，该方法产生的Link对象中的socket却是block模式
2，类似的Link又包含了监听和accept工厂方法，该监听使用socket也是block模式的，一直没有切成non-block的，该项影响不大，因为后续accept是由fde中的事件通知驱动。并且Link::accept()中没有检查fd耗尽的情况，在while循环中会有死循环的风险
3，Server的accept事件其实也算是一种read事件，没必要单独判断一下
4，IO事件本身是由fde检产生的，放在fde中进行分发要自然些
5，Server/Link都是事件具体的响应者，可将对应的事件从fde中直接分发到具体对象，因此可将Server.cpp中的多个*_session方法分拆到具体的功能对象中
6，总结一句：fde专职进行IO事件检测，并将其分发到Sever/Link中，而Server/Link专心处理对应的事件就好，这个差不多就是EventLoop的模型架构了

班门弄斧的意见，请勿见笑！

**Comment by ideawu** [comment]
> 并且Link::accept()中没有检查fd耗尽的情况，在while循环中会有死循环的风险

**Comment by lanyuliuyun** [comment]
对，此处是包含了fd耗尽的情况！不过仍然有一个问题：当fd耗尽时，accept会反复失败，使得Server::loop_once()因accept_session()导致流程空转，效果类似于死循环！
